### ISSUE TITLE
2.0 Feedback

### ISSUE THREAD

**Issue by lucasrowe** [redbluegames/unity-bulk-rename#79]
Here are some of my initial UX thoughts in no particular order. Will actually use the tool in the next couple days. Overall this is really solid and public ready IMO.

1. Left panel should accommodate all labels (regular expression labels are cut off). Can it be a higher priority than the drag and drop panel so that no matter how narrow the window goes, the left panel has a minimum width?
2. "Original Name" could be called "Diffed Name" or something? The Show Name as Diff at the bottom would be more clear too.
3. The "Add more objects by dragging them here." tip is very small and hard to see. And nowhere close to where your eyes most likely are (at the top of the panel).
4. When the list is full, the "Add more object..." tip is off screen (presumably they now know how to use it so that's minor). More importantly, the user doesn't get a lot of feedback when they add more because new objects also go to the bottom, out of the scroll view. Perhaps the window could scroll to the bottom when objects are dragged in?

![renamer](https://user-images.githubusercontent.com/398359/27650181-14c5e1fc-5c02-11e7-9df5-8a9c42e37522.PNG)

**Comment by edwardrowe** [comment]
I addressed most of this. For the labels, I just shorted the labels when the Regex is selected. The best fix would be a resizable panel, so I'm gonna hold out for that some day. I made the Show Diff toggle change the header for the original name, and I scrolled the Preview Panel to the bottom when objects are added.

I did not address the drag objects label because it doesn't really bother me. I tried putting it centered in the empty space, but it annoyed me that it moved. Like you said, once people learn they can continue to drag objects in, it is actually better for it to be out of the way.
